version: "3"
services:
  zoo1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    volumes:
      - "zoo1_data:/data"
      - "zoo1_datalog:/datalog"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          "ruok",
          "|",
          "nc",
          "localhost",
          "2181",
          "|",
          "grep",
          "imok",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zoo1
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - "kafka1_data:/var/lib/kafka/data"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms256m -XX:+UseG1GC"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - kafka-net
  kafka-ui:
    image: provectuslabs/kafka-ui:latest # or use a specific version
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:19092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zoo1:2181"
    networks:
      - kafka-net
    depends_on:
      - kafka1
  notify-app:
    build: ./notificationService
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKER: kafka1:19092
    networks:
      - kafka-net
    depends_on:
      - kafka1
networks:
  kafka-net:
    driver: bridge
volumes:
  zoo1_data:
  zoo1_datalog:
  kafka1_data:
